import Header from "@/components/Header";
import Main from "@/components/Main";
import { CssBaseline } from "@mui/material";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CssBaseline />
        <Header />
        {children}
      </body>
    </html>
  );
}
